import React from 'react'
import Button from './Button'

const Keypad = ({handleClick}) => (
  <div>
    <Button
      name="+"
      onClick={handleClick}
    />
    <Button
      name="-"
      onClick={handleClick}
    />
    <Button
      name="*"
      onClick={handleClick}
    />
    <Button
      name="/"
      onClick={handleClick}
    />
    <Button
      name="1"
      onClick={handleClick}
    />
    <Button
      name="2"
      onClick={handleClick}
    />
    <Button
      name="3"
      onClick={handleClick}
    />
    <Button
      name="4"
      onClick={handleClick}
    />
    <Button
      name="5"
      onClick={handleClick}
    />
    <Button
      name="6"
      onClick={handleClick}
    />
    <Button
      name="7"
      onClick={handleClick}
    />
    <Button
      name="8"
      onClick={handleClick}
    />
    <Button
      name="9"
      onClick={handleClick}
    />
    <Button
      name="0"
      onClick={handleClick}
    />
    <Button
      name="n"
      onClick={handleClick}
    />
    <Button
      name="b"
      onClick={handleClick}
    />
    <Button
      name="="
      onClick={handleClick}
    />
    <Button
      name="."
      onClick={handleClick}
    />
    <Button
      name="c"
      onClick={handleClick}
    />   
  </div>
)

export default Keypad